### PR TITLE
added: tests for django-1.6, django-1.7, django-trunk

### PR DESCRIPTION
**Pull request by conrado**

### CODE REVIEW

**Comment by galuszkak** [comment]
Could be this merged?

**Comment by jrief** [comment]
Thanks

**Comment by jrief** [comment]
Travis reports a broken built:
https://travis-ci.org/divio/django-shop/jobs/56893025

can you please fix this?

**Comment by conrado** [comment]
#281

**Comment by conrado** [comment]
#285

**Pull request merged**
